version: 2

models:
  - name: mart_trip_features
    columns:
      - name: trip_id
        data_tests: [unique, not_null]
      - name: is_high_tip
        data_tests:
          - accepted_values:
              arguments:
                values: [0, 1]
      - name: trip_distance
        data_tests: [not_null]
      - name: fare_per_mile
        data_tests: [not_null]
      - name: trip_duration_min
        data_tests: [not_null]