yellowtaxi_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: taxi
      password: taxi
      dbname: taxi_db
      schema: staging
      threads: 4
